name: Deploy site

on:
  push:
    branches:
      - master

jobs:
  deploy:
    name: Deploy
    runs-on: ubuntu-latest
    steps:
      - name: Create temporary files
        run: |
          MY_WORKSPACE=$(mktemp --tmpdir=$GITHUB_WORKSPACE -d tarball-XXXXX)
          MY_WORKSPACE_NAME=${MY_WORKSPACE##"$GITHUB_WORKSPACE/"}
          echo "MY_WORKSPACE=$MY_WORKSPACE" >> $GITHUB_ENV
          echo "MY_WORKSPACE_NAME=$MY_WORKSPACE_NAME" >> $GITHUB_ENV
          echo "GITHUB_ENV: $GITHUB_ENV"
          echo "cat GITHUB_ENV"
          cat $GITHUB_ENV

      - name: Upload to Azure blob storage
        uses: azure/CLI@v1
        with:
          azcliversion: 2.0.72
          inlineScript: |
               echo "githubenv: ${GITHUB_ENV}"
               
               echo "ls github env"
               ls -hal $GITHUB_ENV
               
               echo "cat github env"
               cat $GITHUB_ENV

               echo "export"
               export

               echo "ls github workspace"
               ls $GITHUB_WORKSPACE

#               ls $GITHUB_WORKSPACE
#              az storage blob upload-batch --sas-token '${{ secrets.AZURE_SAS_TOKEN }}' --account-name 'szemerestorage2' --source content/ --destination '$web/test'
