name: Deploy site

on:
  push:
    branches:
      - master

jobs:
  deploy:
    name: Deploy
    runs-on: ubuntu-latest
    steps:
      - name: Create temporary files
        run:
          MY_WORKDIR=$(mktemp --tmpdir=$GITHUB_WORKSPACE -d tarball-XXXXX)

      - name: Upload to Azure blob storage
        uses: azure/CLI@v1
        with:
          azcliversion: 2.0.72
          inlineScript: |
               ls $GITHUB_WORKSPACE

#              az storage blob upload-batch --sas-token '${{ secrets.AZURE_SAS_TOKEN }}' --account-name 'szemerestorage2' --source content/ --destination '$web/test'
