name: Matrix test

on:
  push:
    branches:
      - master

jobs:
  myjob:
    name: My Job
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        foo:
          - [ubuntu-focal,  deb ]
          - [ubuntu-xenial,  deb ]
          - [fedora-33,      rpm ]
          - [fedora-32,      rpm ]
    env:
      DISTRIBUTION: ${{ matrix.foo[0] }}
      PACKAGE_MANAGER: ${{ matrix.foo[1] }}
    steps:
      - name: First step
        run: |
          echo "matrix-distribution-0: $DISTRIBUTION"
          echo "matrix-distribution-1: $PACKAGE_MANAGER"

      - name: Second step
        if: env.PACKAGE_MANAGER == 'deb'
        run: |
          echo "matrix-distribution-0: $DISTRIBUTION"
          echo "matrix-distribution-1: $PACKAGE_MANAGER"
